CMS-Bookstore - Milestone 2
udberg/Magic-Books pull request #2
Opened 2021-07-12 23:59 UTC by udberg

In this milestone, I initialized the Redux actions, reducers, and store. Additionally, l also defined empty React components and separated presentation and container components.

I also added two container components (those which connect with the Redux store): BooksList and BooksForm
and two presentational components: App and Book.

2021-07-13 09:57 UTC, afanimartin requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this PR. You did well with most requirements.
### Highlights 🌵 🌵 🌵 
- `Book` and `BookList` components well implemented
- readme looks professional

### Change(s) 🔕 🔕 🔕 
- delete `DS_Store` folder
- render the `BookList` and `BookForm` components wrapped in `div` tags in the `App` component.
```
const App = () => {
 <div>
  <BookList />
  <BookForm />
 </div>
}
```
- Move the `BookList` component to the `containers` where it rightly belongs
- Check comments for suggestions


### Martin Afani
#### Slack: whiz25

2021-07-13 09:57 UTC, afanimartin commented on src/index.js
> +
- Wrap the `App` component in a `Provider`
```
const MainApp = () => {
<Provider store={store}>
  <App />
<Provider />
```
- Add sample book object to the initial state object
```
const initialBook = {'title': 'title', 'author': 'some author'}
super();
this.state = {
book: initialBook
}
// now add the book as a prop to App component
```

2021-07-13 09:57 UTC, afanimartin commented on src/components/BookList.js
> +                    />
- You should be rendering the `Book` component instead. The `BookContainer` component is unnecessary and doesn't have the props, `id`, `title`, `category`, `removeBook` but the `Book`.

2021-07-13 09:57 UTC, afanimartin commented on src/components/BooksForm.js
> +class BooksForm extends Component {
- Move this component to the `src/containers` folder where it rightly makes sense
- Add a constant with book categories. Something like
```
const categories = ['code', 'comedy'], etc
```

2021-07-13 14:59 UTC, trekab requested changes
### Changes Required! :recycle: 
Hi @udberg! It appears that most of the suggested changes from the last review were not implemented i.e. : 
- [x] Your `App` component renders `<h1>Hello World</h1>` instead of the expected `BookList` and `BookForm` components. ([screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/App/AppWrapBookListAndBookForm.png))
- [x] `BookList` and `BookForm` should be in your `src/containers` folder.
- [ ] Add initial state and use `Provider` to wrap your `App` component in your `src/index.js` file as highlighted in the last review.

__N.B:__ Don't hesitate to reach out in case you find this feedback unclear in any way!

_Please make the necessary changes and submit another code review request._
__[Treasure Kabareebe](https://trekab.github.io)__

2021-07-13 17:33 UTC, rukundoeric commented
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - Follows gitwork-flow.  💯
  - Codebase looks clean and professional. 💯 

- ### To Improve
  - [ ] [MANDATORY] When I try to start you app, it is throwing the following error...
  ![Screen Shot 2021-07-13 at 19 28 50](https://user-images.githubusercontent.com/45217364/125498840-739c316b-d500-4113-997c-6627c8ff6b33.png)


_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-07-14 08:53 UTC, afanimartin approved these changes
## Approved 👍🏿 👍🏿 👍🏿 
Nice work making the requested change. No errors/warnings are shown in the console. Well done.


### Martin Afani
#### Slack: whiz25

2021-07-14 09:05 UTC, merged